;;; agent-shell-cockpit-design-test.el --- Workspace UX regressions -*- lexical-binding: t; -*-

(require 'agent-shell-cockpit-test-helper)
(require 'agent-shell-cockpit-lifecycle-test)

(ert-deftest cockpit-launch-toggles-and-reorders-without-starting ()
  (let ((agent-shell-cockpit-instructions
         '((brief :title "Brief" :source (literal "FIRST"))
           (skill :title "Review skill" :source (skill "reviewer"))
           (style :title "Style" :source (literal "LAST"))))
        (agent-shell-cockpit-default-instructions '(brief skill style))
        (agent-shell-cockpit-refresh-interval nil))
    (with-temp-buffer
      (agent-shell-cockpit-launch-mode)
      (setq agent-shell-cockpit-launch--items (agent-shell-cockpit-launch--initial-items nil))
      (agent-shell-cockpit-launch-refresh)
      (goto-char (point-min)) (search-forward "Review skill")
      (agent-shell-cockpit-launch-move-up)
      (should (eq (plist-get (agent-shell-cockpit-ui-object-at-point) :id) 'skill))
      (should (equal (agent-shell-cockpit-launch-render)
                     "Use the reviewer skill.\n\nFIRST\n\nLAST"))
      (agent-shell-cockpit-launch-toggle)
      (should (equal (agent-shell-cockpit-launch-render) "FIRST\n\nLAST"))
      (agent-shell-cockpit-launch-toggle)
      (should (string-prefix-p "Use the reviewer skill." (agent-shell-cockpit-launch-render))))))

(ert-deftest cockpit-launch-multiple-briefs-and-selected-worktrees ()
  (cockpit-test-with-worktree
   (let ((first (expand-file-name "context/first.org" (map-elt workspace 'root)))
         (second (expand-file-name "context/second.org" (map-elt workspace 'root)))
         (agent-shell-cockpit-refresh-interval nil)
         (agent-shell-cockpit-instructions nil))
     (with-temp-file first (insert "PRIVATE FIRST BODY"))
     (with-temp-file second (insert "PRIVATE SECOND BODY"))
     (with-temp-buffer
       (agent-shell-cockpit-launch-mode)
       (setq default-directory (map-elt workspace 'root)
             agent-shell-cockpit-launch--target (agent-shell-cockpit-session-target default-directory workspace)
             agent-shell-cockpit-launch--worktrees
             '((:id "service" :title "service" :enabled t)
               (:id "not-selected" :title "not-selected" :enabled nil)))
       (agent-shell-cockpit-launch-add-file first)
       (agent-shell-cockpit-launch-add-file second)
       (let ((text (agent-shell-cockpit-launch-render)))
         (should (string-match-p "worktrees/service" text))
         (should-not (string-match-p "not-selected\|PRIVATE" text))
         (should (< (string-match "first.org" text) (string-match "second.org" text))))
       (goto-char (point-min)) (search-forward "service")
       (agent-shell-cockpit-launch-toggle)
       (should (string-prefix-p "No worktrees are assigned" (agent-shell-cockpit-launch-render)))))))

(ert-deftest cockpit-navigation-prefers-buffer-association-and-remembers-visit ()
  (agent-shell-cockpit-test-with-root
   (let* ((a (agent-shell-cockpit-workspace-create :name "a"))
          (b (agent-shell-cockpit-workspace-create :name "b"))
          (agent-shell-cockpit-recent-workspaces (list (map-elt b 'root)))
          opened)
     (with-temp-buffer
       (setq default-directory (map-elt a 'root))
       (cl-letf (((symbol-function 'agent-shell-cockpit-workspace-view)
                  (lambda (workspace) (setq opened (map-elt workspace 'name)))))
         (agent-shell-cockpit)
         (should (equal opened "a"))
         (setq-local agent-shell-cockpit-session-workspace-root (map-elt b 'root))
         (agent-shell-cockpit)
         (should (equal opened "b"))
         (setq agent-shell-cockpit-session-workspace-root nil default-directory test-root)
         (agent-shell-cockpit)
         (should (equal opened "b")))))))

(ert-deftest cockpit-selected-worktrees-survive-metadata-roundtrip ()
  (agent-shell-cockpit-test-with-root
   (let ((workspace (agent-shell-cockpit-workspace-create :name "a")))
     (agent-shell-cockpit-store-set workspace 'sessions
                                    '(((agentId . "test") (sessionId . "one")
                                       (selectedWorktrees . ("backend" "shared")))
                                      ((agentId . "test") (sessionId . "two") (selectedWorktrees))))
     (agent-shell-cockpit-store-write workspace)
     (let ((sessions (map-elt (agent-shell-cockpit-store-read (map-elt workspace 'root)) 'sessions)))
       (should (equal (map-elt (car sessions) 'selectedWorktrees) '("backend" "shared")))
       (should-not (map-elt (cadr sessions) 'selectedWorktrees))))))

(ert-deftest cockpit-archive-confirmation-decline-keeps-files-and-metadata ()
  (cockpit-test-with-worktree
   (with-temp-file (expand-file-name "local.txt" worktree) (insert "Local work"))
   (let (prompt)
     (cl-letf (((symbol-function 'yes-or-no-p)
                (lambda (text) (setq prompt text) nil)))
       (should-not (agent-shell-cockpit-workspace-archive-confirm workspace)))
     (should (string-match-p "service:.*will be deleted" prompt))
     (should (file-exists-p (expand-file-name "local.txt" worktree)))
     (should-not (map-elt (agent-shell-cockpit-store-read (map-elt workspace 'root)) 'operation)))))

(ert-deftest cockpit-archive-confirmed-dirty-locked-worktree-is-removed ()
  (cockpit-test-with-worktree
   (with-temp-file (expand-file-name "README.md" worktree) (insert "Uncommitted"))
   (with-temp-file (expand-file-name "local.txt" worktree) (insert "Untracked"))
   (agent-shell-cockpit-test-git source "worktree" "lock" worktree)
   (let (archive prompt)
     (cl-letf (((symbol-function 'yes-or-no-p) (lambda (text) (setq prompt text) t)))
       (setq archive (agent-shell-cockpit-workspace-archive-confirm workspace)))
     (should (string-match-p "locked" prompt))
     (should-not (file-exists-p worktree))
     (should-not (string-match-p (regexp-quote worktree)
                                 (agent-shell-cockpit-test-git source "worktree" "list" "--porcelain")))
     (agent-shell-cockpit-workspace-restore archive)
     (should-not (file-exists-p (expand-file-name "local.txt" worktree)))
     (with-temp-buffer
       (insert-file-contents (expand-file-name "README.md" worktree))
       (should (equal (buffer-string) "test\n"))))))

(ert-deftest cockpit-archive-force-still-protects-unsaved-buffers ()
  (cockpit-test-with-worktree
   (let ((buffer (find-file-noselect (expand-file-name "README.md" worktree))))
     (unwind-protect
         (with-current-buffer buffer
           (insert "Unsaved")
           (should-error (agent-shell-cockpit-workspace-archive workspace t) :type 'user-error)
           (should (file-directory-p worktree)))
       (with-current-buffer buffer (set-buffer-modified-p nil))
       (kill-buffer buffer)))))

(ert-deftest cockpit-restore-deleted-branch-recovers-retained-commit-after-gc ()
  (cockpit-test-with-worktree
   (agent-shell-cockpit-test-git worktree "switch" "-c" "temporary-branch")
   (with-temp-file (expand-file-name "unique" worktree) (insert "Committed work"))
   (agent-shell-cockpit-test-git worktree "add" ".")
   (agent-shell-cockpit-test-git worktree "commit" "-qm" "unique")
   (let* ((head (agent-shell-cockpit-test-git worktree "rev-parse" "HEAD"))
          (archive (agent-shell-cockpit-workspace-archive workspace)))
     (should (equal (map-elt (car (map-elt archive 'worktrees)) 'branch) "temporary-branch"))
     (agent-shell-cockpit-test-git source "branch" "-D" "temporary-branch")
     (agent-shell-cockpit-test-git source "reflog" "expire" "--expire=now" "--all")
     (agent-shell-cockpit-test-git source "gc" "--prune=now")
     (agent-shell-cockpit-workspace-restore archive)
     (should (equal head (agent-shell-cockpit-test-git worktree "rev-parse" "HEAD")))
     (should (equal "" (agent-shell-cockpit-test-git worktree "branch" "--show-current"))))))

(ert-deftest cockpit-restore-reuses-unchanged-branch ()
  (cockpit-test-with-worktree
   (agent-shell-cockpit-test-git worktree "switch" "-c" "kept-branch")
   (agent-shell-cockpit-workspace-restore (agent-shell-cockpit-workspace-archive workspace))
   (should (equal "kept-branch" (agent-shell-cockpit-test-git worktree "branch" "--show-current")))))

(ert-deftest cockpit-unavailable-repository-does-not-block-workspace-restore ()
  (cockpit-test-with-worktree
   (let* ((archive (agent-shell-cockpit-workspace-archive workspace))
          (moved (concat source "-moved")))
     (rename-file source moved)
     (let ((restored (agent-shell-cockpit-workspace-restore archive)))
       (should (equal (map-elt restored 'state) "active"))
       (should (map-elt (car (map-elt restored 'worktrees)) 'restoreError))
       ;; A partially restored workspace can also be archived again.
       (setq archive (agent-shell-cockpit-workspace-archive restored))
       (rename-file moved source)
       (setq restored (agent-shell-cockpit-workspace-restore archive))
       (should-not (map-elt (car (map-elt restored 'worktrees)) 'restoreError))
       (should (file-directory-p worktree))))))

(ert-deftest cockpit-archive-confirm-recovers-after-directory-move ()
  (cockpit-test-with-worktree
   (let ((rename (symbol-function 'agent-shell-cockpit-lifecycle--rename)))
     (cl-letf (((symbol-function 'agent-shell-cockpit-lifecycle--rename)
                (lambda (from to)
                  (funcall rename from to)
                  (error "Crash after rename"))))
       (should-error (agent-shell-cockpit-workspace-archive workspace)))
     (let ((partial (car (agent-shell-cockpit-store-discover t))))
       (should (equal (map-nested-elt partial '(operation type)) "archive"))
       (cl-letf (((symbol-function 'yes-or-no-p) (lambda (&rest _) t)))
         (should-not (map-elt (agent-shell-cockpit-workspace-archive-confirm partial) 'operation)))))))

(ert-deftest cockpit-restore-does-not-rewind-moved-branch ()
  (cockpit-test-with-worktree
   (agent-shell-cockpit-test-git worktree "switch" "-c" "moved-branch")
   (let* ((saved (agent-shell-cockpit-test-git worktree "rev-parse" "HEAD"))
          (archive (agent-shell-cockpit-workspace-archive workspace)))
     (with-temp-file (expand-file-name "new" source) (insert "Later work"))
     (agent-shell-cockpit-test-git source "add" ".")
     (agent-shell-cockpit-test-git source "commit" "-qm" "later")
     (agent-shell-cockpit-test-git source "branch" "-f" "moved-branch" "HEAD")
     (let ((later (agent-shell-cockpit-test-git source "rev-parse" "moved-branch")))
       (agent-shell-cockpit-workspace-restore archive)
       (should (equal saved (agent-shell-cockpit-test-git worktree "rev-parse" "HEAD")))
       (should (equal later (agent-shell-cockpit-test-git source "rev-parse" "moved-branch")))
       (should (equal "" (agent-shell-cockpit-test-git worktree "branch" "--show-current")))))))

(ert-deftest cockpit-all-agents-returns-to-origin-workspace ()
  (agent-shell-cockpit-test-with-root
   (let* ((workspace (agent-shell-cockpit-workspace-create :name "alpha"))
          (agent-shell-cockpit-refresh-interval nil)
          (agent-shell-cockpit-agents-view-buffer-name " *all-agents test*")
          workspace-buffer agents-buffer)
     (unwind-protect
         (save-window-excursion
           (agent-shell-cockpit-workspace-view workspace)
           (setq workspace-buffer (current-buffer))
           (agent-shell-cockpit-all-agents)
           (setq agents-buffer (current-buffer))
           (should (derived-mode-p 'agent-shell-cockpit-agents-view-mode))
           (should-not (string-match-p "Workspaces (" (buffer-string)))
           (agent-shell-cockpit-quit)
           (should (eq (current-buffer) workspace-buffer))
           (dolist (binding '(("w" . agent-shell-cockpit-create-workspace)
                              ("l" . agent-shell-cockpit-archives)
                              ("E" . agent-shell-cockpit-repair-workspace)))
             (should (eq (lookup-key (current-local-map) (car binding)) (cdr binding)))))
       (dolist (buffer (list workspace-buffer agents-buffer))
         (when (buffer-live-p buffer) (kill-buffer buffer)))))))

(ert-deftest cockpit-navigation-repairs-invalid-metadata-without-workspace-list ()
  (agent-shell-cockpit-test-with-root
   (let* ((workspace (agent-shell-cockpit-workspace-create :name "broken"))
          (root (map-elt workspace 'root))
          (metadata (agent-shell-cockpit-store-metadata-path root))
          opened)
     (with-temp-file metadata (insert "{broken"))
     (cl-letf (((symbol-function 'completing-read) (lambda (_prompt choices &rest _) (caar choices)))
               ((symbol-function 'yes-or-no-p) (lambda (&rest _) t))
               ((symbol-function 'agent-shell-cockpit-workspace-view) (lambda (record) (setq opened record))))
       (agent-shell-cockpit-repair-workspace))
     (should (equal (map-elt opened 'root) root))
     (should (eq (map-elt (agent-shell-cockpit-store-read root) 'kind) 'workspace))
     (should (directory-files (file-name-directory metadata) nil "backup-")))))

(ert-deftest cockpit-other-agents-collapsed-filtered-actionable-and-refresh-stable ()
  (agent-shell-cockpit-test-with-root
   (let* ((workspace (agent-shell-cockpit-workspace-create :name "here"))
          (other-workspace (agent-shell-cockpit-workspace-create :name "elsewhere"))
          (own (generate-new-buffer " *own agent*"))
          (other (generate-new-buffer " *other agent*"))
          (standalone (generate-new-buffer " *standalone agent*"))
          (agent-shell-cockpit-test--buffers (list own standalone other))
          (agent-shell-cockpit-refresh-interval nil))
     (unwind-protect
         (progn
           (dolist (pair (list (cons own workspace) (cons other other-workspace)))
             (with-current-buffer (car pair)
               (setq default-directory (map-elt (cdr pair) 'root)
                     agent-shell-cockpit-session-workspace-root default-directory)))
           (with-current-buffer standalone (setq default-directory test-root))
           (cl-letf (((symbol-function 'agent-shell-cockpit-session-status)
                      (lambda (buffer) (if (eq buffer other) 'attention 'working))))
             (with-temp-buffer
               (agent-shell-cockpit-workspace-view-mode)
               (setq agent-shell-cockpit-workspace-view--root (map-elt workspace 'root))
               (agent-shell-cockpit-workspace-view-refresh)
               (let ((section (car (oref magit-root-section children))))
                 (should (eq (oref section value) 'other-agents))
                 (should (oref section hidden))
                 (should (string-match-p "Other agents · 1 needs attention"
                                         (buffer-string)))
                 (should (eq (get-text-property (oref section start) 'font-lock-face)
                             'agent-shell-cockpit-other-agents-attention))
                 (goto-char (oref section start))
                 (agent-shell-cockpit-toggle-section)
                 (agent-shell-cockpit-workspace-view-refresh)
                 (setq section (car (oref magit-root-section children)))
                 (should-not (oref section hidden))
                 (should (equal (mapcar (lambda (child) (oref child object)) (oref section children))
                                (list other standalone)))
                 (should (string-match-p "elsewhere" (buffer-string)))
                 (save-window-excursion
                   (switch-to-buffer (current-buffer))
                   (goto-char (oref (car (oref section children)) start))
                   (let ((origin (current-buffer)))
                     (should (eq (agent-shell-cockpit-agent-buffer-at-point) other))
                     (agent-shell-cockpit-open)
                     (should (eq (current-buffer) other))
                     (agent-shell-cockpit-session-return)
                     (should (eq (current-buffer) origin))))
                 (goto-char (oref section start))
                 (agent-shell-cockpit-toggle-section)
                 (agent-shell-cockpit-workspace-view-refresh)
                 (should (oref (car (oref magit-root-section children)) hidden))))))
       (dolist (buffer (list own other standalone)) (kill-buffer buffer))))))

(ert-deftest cockpit-workspace-shortcuts-have-no-global-agent-W-binding ()
  (dolist (map (list agent-shell-cockpit-workspace-view-mode-map
                    agent-shell-cockpit-agents-view-mode-map
                    agent-shell-cockpit-archive-view-mode-map))
    (should-not (lookup-key map "W"))))

(ert-deftest cockpit-launch-rebuilds-defaults-and-context-without-leaking-state ()
  (agent-shell-cockpit-test-with-root
   (let* ((a (agent-shell-cockpit-workspace-create :name "a"))
          (b (agent-shell-cockpit-workspace-create :name "b"))
          (a-file (expand-file-name "context/a.org" (map-elt a 'root)))
          (b-file (expand-file-name "context/b.org" (map-elt b 'root)))
          (later (expand-file-name "context/later.org" (map-elt a 'root)))
          (agent-shell-cockpit-refresh-interval nil)
          (agent-shell-cockpit-instructions
           '((one :title "One" :source (skill "one"))
             (two :title "Two" :source (skill "two"))))
          (agent-shell-cockpit-default-instructions '(one))
          a-buffer b-buffer)
     (with-temp-file a-file (insert "A"))
     (with-temp-file b-file (insert "B"))
     (unwind-protect
         (save-window-excursion
           (agent-shell-cockpit-launch a)
           (setq a-buffer (current-buffer))
           (should (equal (plist-get (car (last agent-shell-cockpit-launch--items)) :source)
                          '(file "context/a.org")))
           ;; Simulate a previous prompt's toggles, ordering, and extra files.
           (dolist (item agent-shell-cockpit-launch--items)
             (setf (plist-get item :enabled) (eq (plist-get item :id) 'two)))
           (setq agent-shell-cockpit-launch--items (reverse agent-shell-cockpit-launch--items))
           (agent-shell-cockpit-launch-add-file b-file)
           (agent-shell-cockpit-launch-preview)
           (with-temp-file later (insert "Later"))
           (agent-shell-cockpit-launch a)
           (should (eq (current-buffer) a-buffer))
           (should (eq (plist-get (car agent-shell-cockpit-launch--items) :id) 'one))
           (should (plist-get (car agent-shell-cockpit-launch--items) :enabled))
           (should-not (plist-get (seq-find (lambda (item) (eq (plist-get item :id) 'two))
                                           agent-shell-cockpit-launch--items) :enabled))
           (let ((text (agent-shell-cockpit-launch-render)))
             (should (string-match-p "context/a.org" text))
             (should (string-match-p "context/later.org" text))
             (should-not (string-match-p "context/b.org" text)))
           (with-current-buffer "*Cockpit launch preview*"
             (should-not (string-match-p "context/b.org" (buffer-string))))
           (agent-shell-cockpit-launch b)
           (setq b-buffer (current-buffer))
           (let ((text (agent-shell-cockpit-launch-render)))
             (should (string-match-p "context/b.org" text))
             (should-not (string-match-p "context/a.org" text)))
           (should (equal agent-shell-cockpit-default-instructions '(one))))
       (dolist (buffer (list a-buffer b-buffer (get-buffer "*Cockpit launch preview*")))
         (when (buffer-live-p buffer) (kill-buffer buffer)))))))

(ert-deftest cockpit-launch-context-defaults-avoid-duplicate-catalog-file ()
  (agent-shell-cockpit-test-with-root
   (let* ((workspace (agent-shell-cockpit-workspace-create :name "a"))
          (file (expand-file-name "context/prompt.org" (map-elt workspace 'root)))
          (agent-shell-cockpit-instructions
           '((brief :title "Brief" :source (file "context/prompt.org")))))
     (with-temp-file file (insert "Brief"))
     (let* ((items (agent-shell-cockpit-launch--initial-items workspace))
            (files (seq-filter (lambda (item) (eq (car (plist-get item :source)) 'file)) items)))
       (should (= (length files) 1))
       (should (eq (plist-get (car files) :id) 'brief))
       (should (plist-get (car files) :enabled))))))

(provide 'agent-shell-cockpit-design-test)
;;; agent-shell-cockpit-design-test.el ends here
